export const PERMISSIONS = {
  CREATE_GOAL: "CREATE_GOAL",
  UPDATE_GOAL: "UPDATE_GOAL",
  DELETE_GOAL: "DELETE_GOAL",

  CREATE_ACTION: "CREATE_ACTION",
  UPDATE_ACTION: "UPDATE_ACTION",

  POST_ANNOUNCEMENT: "POST_ANNOUNCEMENT",
  PIN_ANNOUNCEMENT: "PIN_ANNOUNCEMENT",

  INVITE_MEMBER: "INVITE_MEMBER",
  UPDATE_MEMBER_ROLE: "UPDATE_MEMBER_ROLE",
};

export const ROLE_PERMISSIONS = {
  ADMIN: [
    "CREATE_GOAL",
    "UPDATE_GOAL",
    "DELETE_GOAL",
    "CREATE_ACTION",
    "UPDATE_ACTION",
    "POST_ANNOUNCEMENT",
    "PIN_ANNOUNCEMENT",
    "INVITE_MEMBER",
    "UPDATE_MEMBER_ROLE",
  ],

  MEMBER: [
    "CREATE_GOAL",
    "UPDATE_GOAL",
    "CREATE_ACTION",
    "UPDATE_ACTION",
    "POST_ANNOUNCEMENT",
  ],
};